export const NAT_ID_TYPES = ['PASSPORT_NUMBER', 'NATIONAL_IDENTITY_NUMBER', 'SOCIAL_SECURITY_NUMBER', 'TAX_IDENTIFICATION_NUMBER', 'ALIEN_REGISTRATION_NUMBER', 'DRIVERS_LICENSE_NUMBER', 'OTHER'];
export const JUR_ID_TYPES = ['COUNTRY_IDENTIFICATION_NUMBER', 'TAX_IDENTIFICATION_NUMBER', 'CERTIFICATE_OF_INCORPORATION_NO', 'LEGAL_ENTITY_IDENTIFIER', 'BANK_PARTY_IDENTIFICATION', 'OTHER'];
export const COUNTERPARTY_TYPES = ['ORIGINATOR', 'BENEFICIARY'];
