// import { Transfer, TransferStatus, TransferType } from '../../core/models/transaction.model';
//
// export const TRANSACTION_DATA: Transfer[] = [
//   {
//     id: 1,
//     type: TransferType.incoming,
//     date: '12-12-2020',
//     status: TransferStatus.approved,
//     counterparty: 'Test',
//     amount: 1.2,
//     asset: 'BTC',
//     comment: 'Test',
//     sessionId: 1,
//     originator: 'Test',
//     originatorVasp: 'Test',
//     originatorVaan: 'Test',
//     originatorAddress: 'Test',
//     originatorPostal: 'Test',
//     originatorBirth: 'Test',
//     beneficiary: 'Test',
//     beneficiaryVasp: 'Test',
//     beneficiaryVaan: 'Test',
//     beneficiaryAddress: 'Test',
//     destinationAddress: 'Test',
//     transactionHash: 'Test',
//     sendingAddress: 'Test'
//   },
//   {
//     id: 2,
//     type: TransferType.incoming,
//     date: '12-12-2020',
//     status: TransferStatus.approved,
//     counterparty: 'Test',
//     amount: 1.2,
//     asset: 'BTC',
//     comment: 'Test',
//     sessionId: 1,
//     originator: 'Test',
//     originatorVasp: 'Test',
//     originatorVaan: 'Test',
//     originatorAddress: 'Test',
//     originatorPostal: 'Test',
//     originatorBirth: 'Test',
//     beneficiary: 'Test',
//     beneficiaryVasp: 'Test',
//     beneficiaryVaan: 'Test',
//     beneficiaryAddress: 'Test',
//     destinationAddress: 'Test',
//     transactionHash: 'Test',
//     sendingAddress: 'Test'
//   },
//   {
//     id: 3,
//     type: TransferType.incoming,
//     date: '12-12-2020',
//     status: TransferStatus.approved,
//     counterparty: 'Test',
//     amount: 1.2,
//     asset: 'BTC',
//     comment: 'Test',
//     sessionId: 1,
//     originator: 'Test',
//     originatorVasp: 'Test',
//     originatorVaan: 'Test',
//     originatorAddress: 'Test',
//     originatorPostal: 'Test',
//     originatorBirth: 'Test',
//     beneficiary: 'Test',
//     beneficiaryVasp: 'Test',
//     beneficiaryVaan: 'Test',
//     beneficiaryAddress: 'Test',
//     destinationAddress: 'Test',
//     transactionHash: 'Test',
//     sendingAddress: 'Test'
//   },
//   {
//     id: 4,
//     type: TransferType.incoming,
//     date: '12-12-2020',
//     status: TransferStatus.approved,
//     counterparty: 'Test',
//     amount: 1.2,
//     asset: 'BTC',
//     comment: 'Test',
//     sessionId: 1,
//     originator: 'Test',
//     originatorVasp: 'Test',
//     originatorVaan: 'Test',
//     originatorAddress: 'Test',
//     originatorPostal: 'Test',
//     originatorBirth: 'Test',
//     beneficiary: 'Test',
//     beneficiaryVasp: 'Test',
//     beneficiaryVaan: 'Test',
//     beneficiaryAddress: 'Test',
//     destinationAddress: 'Test',
//     transactionHash: 'Test',
//     sendingAddress: 'Test'
//   },
//   {
//     id: 5,
//     type: TransferType.incoming,
//     date: '12-12-2020',
//     status: TransferStatus.approved,
//     counterparty: 'Test',
//     amount: 1.2,
//     asset: 'BTC',
//     comment: 'Test',
//     sessionId: 1,
//     originator: 'Test',
//     originatorVasp: 'Test',
//     originatorVaan: 'Test',
//     originatorAddress: 'Test',
//     originatorPostal: 'Test',
//     originatorBirth: 'Test',
//     beneficiary: 'Test',
//     beneficiaryVasp: 'Test',
//     beneficiaryVaan: 'Test',
//     beneficiaryAddress: 'Test',
//     destinationAddress: 'Test',
//     transactionHash: 'Test',
//     sendingAddress: 'Test'
//   },
//   {
//     id: 6,
//     type: TransferType.incoming,
//     date: '12-12-2020',
//     status: TransferStatus.approved,
//     counterparty: 'Test',
//     amount: 1.2,
//     asset: 'BTC',
//     comment: 'Test',
//     sessionId: 1,
//     originator: 'Test',
//     originatorVasp: 'Test',
//     originatorVaan: 'Test',
//     originatorAddress: 'Test',
//     originatorPostal: 'Test',
//     originatorBirth: 'Test',
//     beneficiary: 'Test',
//     beneficiaryVasp: 'Test',
//     beneficiaryVaan: 'Test',
//     beneficiaryAddress: 'Test',
//     destinationAddress: 'Test',
//     transactionHash: 'Test',
//     sendingAddress: 'Test'
//   },
//   {
//     id: 7,
//     type: TransferType.incoming,
//     date: '12-12-2020',
//     status: TransferStatus.approved,
//     counterparty: 'Test',
//     amount: 1.2,
//     asset: 'BTC',
//     comment: 'Test',
//     sessionId: 1,
//     originator: 'Test',
//     originatorVasp: 'Test',
//     originatorVaan: 'Test',
//     originatorAddress: 'Test',
//     originatorPostal: 'Test',
//     originatorBirth: 'Test',
//     beneficiary: 'Test',
//     beneficiaryVasp: 'Test',
//     beneficiaryVaan: 'Test',
//     beneficiaryAddress: 'Test',
//     destinationAddress: 'Test',
//     transactionHash: 'Test',
//     sendingAddress: 'Test'
//   },
//   {
//     id: 8,
//     type: TransferType.incoming,
//     date: '12-12-2020',
//     status: TransferStatus.approved,
//     counterparty: 'Test',
//     amount: 1.2,
//     asset: 'BTC',
//     comment: 'Test',
//     sessionId: 1,
//     originator: 'Test',
//     originatorVasp: 'Test',
//     originatorVaan: 'Test',
//     originatorAddress: 'Test',
//     originatorPostal: 'Test',
//     originatorBirth: 'Test',
//     beneficiary: 'Test',
//     beneficiaryVasp: 'Test',
//     beneficiaryVaan: 'Test',
//     beneficiaryAddress: 'Test',
//     destinationAddress: 'Test',
//     transactionHash: 'Test',
//     sendingAddress: 'Test'
//   },
//   {
//     id: 9,
//     type: TransferType.incoming,
//     date: '12-12-2020',
//     status: TransferStatus.approved,
//     counterparty: 'Test',
//     amount: 1.2,
//     asset: 'BTC',
//     comment: 'Test',
//     sessionId: 1,
//     originator: 'Test',
//     originatorVasp: 'Test',
//     originatorVaan: 'Test',
//     originatorAddress: 'Test',
//     originatorPostal: 'Test',
//     originatorBirth: 'Test',
//     beneficiary: 'Test',
//     beneficiaryVasp: 'Test',
//     beneficiaryVaan: 'Test',
//     beneficiaryAddress: 'Test',
//     destinationAddress: 'Test',
//     transactionHash: 'Test',
//     sendingAddress: 'Test'
//   },
//   {
//     id: 10,
//     type: TransferType.incoming,
//     date: '12-12-2020',
//     status: TransferStatus.approved,
//     counterparty: 'Test',
//     amount: 1.2,
//     asset: 'BTC',
//     comment: 'Test',
//     sessionId: 1,
//     originator: 'Test',
//     originatorVasp: 'Test',
//     originatorVaan: 'Test',
//     originatorAddress: 'Test',
//     originatorPostal: 'Test',
//     originatorBirth: 'Test',
//     beneficiary: 'Test',
//     beneficiaryVasp: 'Test',
//     beneficiaryVaan: 'Test',
//     beneficiaryAddress: 'Test',
//     destinationAddress: 'Test',
//     transactionHash: 'Test',
//     sendingAddress: 'Test'
//   }
// ];
